apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  initContainers:
  - name: git-sync
    image: k8s.gcr.io/git-sync:v3.1.1
    args:
      - "-ssh"
      - "-repo=git@github.com:leanaiorg/examples"  # ADD REPOSITORY
      - "-dest=examples"
      - "-branch=master"
    env:
    - name: GIT_SYNC_ONE_TIME
      value: "true"
    volumeMounts:
    - name: git-secret
      mountPath: /etc/git-secret
    - name: git-source
      mountPath: /tmp/git
    securityContext:
      runAsUser: 65533 # git-sync user
  containers:
  - name: build-image
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=Dockerfile.model",
          "--context=/workspace/examples/<which example>",   # ADD PATH
          "--destination=<registry url/image>:latest"]   # ADD REPO
    volumeMounts:
    - name: workspace
      mountPath: etc/workspace
    - name: git-source
      mountPath: /workspace
  volumes:
  - name: git-source
    emptyDir: {}
  - name: workspace
  - name: git-secret
    secret:
      secretName: git-creds
      defaultMode: 288
  securityContext:
      fsGroup: 65533 #make SSH key readable
    #volumeMounts:
    #  - name: kaniko-secret
    #    mountPath: /secret
    #env:
    #  - name: GOOGLE_APPLICATION_CREDENTIALS
    #    value: /secret/kaniko-secret.json
  restartPolicy: Never
  #volumes:
    #- name: kaniko-secret
      #secret:
      #  secretName: kaniko-secret
