apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: build-container-
spec:
  entrypoint: build-container
  templates:
  - name: build-container
    container:
      image: gcr.io/kaniko-project/executor:latest
      args: ["--dockerfile=Dockerfile",
          "--context=/workspace/examples/continuous_analytics/4_build",   # ADD PATH
          "--destination=registry.demo.scaleout.se/serve:latest"]   # ADD REPO
      volumeMounts:
      - name: workspace
        mountPath: etc/workspace
      - name: git-source
        mountPath: /workspace
    initContainers:
    - name: git-sync
      image: k8s.gcr.io/git-sync:v3.1.1
      args:
        - "-ssh"
        - "-repo=git@github.com:leanaiorg/examples"  # ADD REPOSITORY
        - "-dest=examples"
        - "-branch=continuous_analytics_pipeline"
      env:
      - name: GIT_SYNC_ONE_TIME
        value: "true"
      volumeMounts:
      #- name: git-secret
      #  mountPath: /etc/git-secret
      - name: git-source
        mountPath: /tmp/git
      securityContext:
        runAsUser: 65533 # git-sync user
  volumes:
    - name: git-source
      emptyDir: {}
    - name: workspace
      emptyDir: {}
