apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: k8s-jobs-
spec:
  entrypoint: deploy-wf
  templates:
  - name: deploy-wf
    resource:                   # indicates that this is a resource template
      action: create            # can be any kubectl action (e.g. create, delete, apply, patch)
      # The successCondition and failureCondition are optional expressions.
      # If failureCondition is true, the step is considered failed.
      # If successCondition is true, the step is considered successful.
      # They use kubernetes label selection syntax and can be applied against any field
      # of the resource (not just labels). Multiple AND conditions can be represented by comma
      # delimited expressions.
      # For more details: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
      #successCondition: status.succeeded > 0
      failureCondition: status.failed > 3
      manifest: |               #put your kubernetes spec here
        apiVersion: openfaas.com/v1alpha2
        kind: Function
        metadata:
          name: <NAME OF SERVICE>
          namespace: <YOUR SERVING NAMESPACE>
        spec:
          name: <NAME OF SERVICE>
          handler: node main.js
          image: <IMAGE OF SERVICE>
          labels:
            com.openfaas.scale.min: "2"  # set min scale
            com.openfaas.scale.max: "15" # set max scale
          annotations:
            current-time: Mon  6 Aug 23:42:00 BST 2018
            next-time: Mon  6 Aug 23:42:00 BST 2019
          environment:
            output: "verbose"
            debug: "true"
          limits:                       # Impose any resource limits/request if desired
            cpu: "200m"
            memory: "1Gi"
          requests:
            cpu: "10m"
            memory: "128Mi"
